files = [
"README.md",
"protocol",
"specifications",
"message_types",
"development/js",
"development/rust",
"development/go",
"software/patchwork",
"software/manyverse",
"software/planetary",
"software/patchfoo",
"software/patchfox",
]