title = "Specifications"
toc_depth = 1

files = [
"README.md",
"bendy-butt-spec",
"envelope-spec",
"private-group-spec",
"ssb-bfe-spec",
"ssb-buttwoo-spec",
"ssb-meta-feed-group-spec",
"ssb-meta-feeds-spec",
"ssb-uri-spec"
]